-- ═══════════════════════════════════════════════════════════════
-- ⚠️ SUPERSEDED — DO NOT RUN THIS FILE
-- ═══════════════════════════════════════════════════════════════
--
-- This file originally granted public (anon key) upload/update/delete
-- access to both storage buckets. That has been replaced entirely by
-- admin-only storage policies in sql/security_hardening.sql.
--
-- IMPORTANT: because Postgres RLS policies are combined with OR logic,
-- if you were to run the original version of this file AFTER running
-- security_hardening.sql, the old permissive policies would coexist
-- alongside the new admin-only ones — and the permissive ones would
-- silently win, giving everyone on the internet upload/delete access
-- to your storage again, even though the "secure" policies still show
-- up in your dashboard looking correct.
--
-- This file is intentionally left with no executable SQL below this
-- point. All storage policies now live in:
--   • sql/security_hardening.sql   (creates admin-only policies)
--   • sql/final_audit_hardening.sql (adds bucket-level size/type limits)
--
-- If you ever need to inspect or modify storage policies, edit those
-- files instead of this one.
-- ═══════════════════════════════════════════════════════════════
